apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-kdbl
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL-Support
    uid: postgres-kdbl
    type: postgres
    access: proxy
    url: postgres:5432
    database: support
    user: kdbl
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: true
